version: '3.8'

services:
  backend:
    build:
      context: ./swe30003-be
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-10000}:10000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./swe30003-fe
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - .env
    depends_on:
      - backend

  db:
    image: postgis/postgis:14-3.3
    container_name: postgres_db
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: